export const weeklyPlans = {
  1: ["🏠 Name recognition", "🏠 Crate training", "🚽 Potty training"],
  2: ["🪑 Sit & Down", "👋 Handling paws/ears/mouth", "🦮 Intro to leash"],
  3: ["🐕 Meet calm dogs", "🔊 New surfaces & sounds", "⏱️ Short training sessions"],
  4: ["📢 Basic recall (indoors)", "🏠 Continue potty/crate", "🚶‍♂️ Social walk (carry if needed)"],
  5: ["✋ Wait & Leave it", "🦮 Loose-leash walking", "🧩 Puzzle toy intro"],
  6: ["⏸️ Sit-Stay & Down-Stay", "📢 Recall indoors", "🚗 Traffic & bike exposure"],
  7: ["🪀 Tug with drop-it", "🔍 Find-it game", "🔊 New sounds/social areas"],
  8: ["📚 Reinforce all basics", "🧩 Puzzle time", "🏠 Crate review"],
  9: ["📢 Recall w/ distractions", "⏸️ Advanced stays", "🎯 Marker word training"],
  10: ["📍 Place command", "🧩 Puzzle toy advanced", "🔄 Spin trick"],
  11: ["👃 Scent games", "🤝 Shake trick", "📚 Review leash & crate"],
  12: ["🙇‍♂️ Bow trick", "🎯 New distractions", "🎯 Clicker practice"],
  13: ["🎯 Mix tricks: combo day", "🥾 Trail walk intro", "😌 Social calm practice"],
  14: ["⏱️ Stays with duration", "🦮 Heel in quiet area", "🥣 Slow feeder puzzle"],
  15: ["🎯 Clicker games", "🎮 Play with purpose", "📍 Place & Stay combo"],
  16: ["☕ Dog-friendly cafe visit", "📢 New location recall", "🪀 Tug with control"],
  // ADVANCED TRAINING PHASE (Weeks 17-26)
  17: ["🎯 Advanced recall training", "🚶‍♂️ Off-leash walking prep", "🧠 Complex puzzle solving"],
  18: ["🏃‍♂️ Agility course basics", "👥 Dog park socialization", "🎪 Trick combinations"],
  19: ["🔍 Advanced scent work", "⏰ Extended stay commands", "🚗 Car travel training"],
  20: ["🎾 Fetch with commands", "🧘‍♂️ Impulse control exercises", "🏠 Boundary training"],
  21: ["🦮 Service dog basics", "📞 Response to name from distance", "🎯 Target training"],
  22: ["🌟 Show off skills", "👨‍👩‍👧‍👦 Family obedience", "🎪 Performance tricks"],
  23: ["🏃‍♂️ Running companion training", "🦴 Advanced food puzzles", "📐 Precision commands"],
  24: ["🚶‍♂️ Urban environment skills", "🔊 Noise desensitization", "🎯 Distance commands"],
  25: ["🏆 Competition preparation", "🧠 Problem-solving tasks", "⚡ Quick response training"],
  26: ["🎪 Advanced trick mastery", "🦮 Public access skills", "📚 Skills assessment"],
  // YOUNG ADULT PHASE (Weeks 27-39)
  27: ["🐕‍🦺 Adult dog responsibilities", "🏠 Household management", "👥 Leadership training"],
  28: ["🎯 Precision obedience", "🏃‍♂️ Exercise routines", "🧠 Mental stimulation games"],
  29: ["🦮 Advanced leash skills", "🏞️ Outdoor adventures", "🎪 Entertainment tricks"],
  30: ["👥 Social etiquette", "🏠 Home alone training", "🔍 Search and find games"],
  31: ["🏆 Skill refinement", "🚗 Travel preparation", "📚 Knowledge consolidation"],
  32: ["🎾 Sport training basics", "🧘‍♂️ Relaxation techniques", "🎯 Focus exercises"],
  33: ["🏃‍♂️ Fitness training", "🧠 Advanced puzzles", "👨‍👩‍👧‍👦 Family integration"],
  34: ["🦮 Therapy dog prep", "💼 Work environment skills", "🎪 Public demonstrations"],
  35: ["🏞️ Nature skills", "🔊 Sound training", "⚡ Emergency commands"],
  36: ["🎯 Specialized training", "🏠 Property protection", "📐 Precise positioning"],
  37: ["🧠 Intelligence tests", "🎾 Advanced games", "👥 Stranger interaction"],
  38: ["🏆 Skill competitions", "🚶‍♂️ Perfect heel", "🔍 Detection training"],
  39: ["🎪 Master performer", "🦮 Guide dog skills", "📚 Complete assessment"],
  // MATURE DOG PHASE (Weeks 40-52)
  40: ["🐕 Mature dog skills", "🏠 Household guardian", "👥 Pack leadership"],
  41: ["🎯 Expert obedience", "🏃‍♂️ Endurance training", "🧠 Complex problems"],
  42: ["🦮 Professional skills", "🎪 Entertainment mastery", "🔍 Expert searching"],
  43: ["🏆 Champion training", "🚗 Travel expert", "📚 Skill maintenance"],
  44: ["👥 Social ambassador", "🏞️ Outdoor expert", "🎾 Game master"],
  45: ["🧘‍♂️ Zen training", "💼 Working dog skills", "⚡ Instant response"],
  46: ["🎯 Precision master", "🏠 Home management", "🔊 Communication expert"],
  47: ["🧠 Genius level tasks", "🎪 Performance artist", "👨‍👩‍👧‍👦 Family cornerstone"],
  48: ["🏆 Award worthy skills", "🦮 Service excellence", "📐 Perfect execution"],
  49: ["🎾 Lifetime athlete", "🔍 Detection expert", "🏞️ Adventure companion"],
  50: ["🐕‍🦺 Senior preparation", "👥 Wisdom sharing", "🧘‍♂️ Peaceful mastery"],
  51: ["🏠 Legacy training", "📚 Knowledge transfer", "🎯 Lifetime achievement"],
  52: ["🎉 One year celebration", "🏆 Master graduate", "💝 Lifetime companion"],
};

export const MAX_WEEKS = 52;