import { StyleSheet } from "react-native";
import { dogThemeColors } from "../constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: dogThemeColors.light,
  },
  mainContent: {
    flex: 1,
    backgroundColor: dogThemeColors.light,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 100,
  },
  // Enhanced header container with dog theme
  enhancedHeaderContainer: {
    marginBottom: 20,
    backgroundColor: dogThemeColors.cardBg,
    borderRadius: 20,
    padding: 20,
    shadowColor: dogThemeColors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 2,
    borderColor: dogThemeColors.lightAccent,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  dogInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  dogInfo: {
    flex: 1,
    justifyContent: "center",
  },
  enhancedDogName: {
    fontSize: 18,
    fontWeight: "700",
    color: dogThemeColors.darkText,
    letterSpacing: 0.3,
  },
  dogDetails: {
    fontSize: 14,
    color: dogThemeColors.mediumText,
    marginTop: 2,
    fontWeight: "500",
  },
  dateTimeContainer: {
    alignItems: "flex-end",
    backgroundColor: dogThemeColors.lightAccent,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
    minWidth: 140,
  },
  currentDate: {
    fontSize: 16,
    fontWeight: "700",
    color: dogThemeColors.darkText,
  },
  currentTime: {
    fontSize: 14,
    color: dogThemeColors.mediumText,
    marginTop: 2,
    fontWeight: "500",
  },
  forceSyncButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: dogThemeColors.cardBg,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 6,
    borderWidth: 1,
    borderColor: dogThemeColors.accent,
  },
  forceSyncText: {
    color: dogThemeColors.primary,
    fontSize: 12,
    fontWeight: "500",
  },
  headerBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: dogThemeColors.lightAccent,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
    marginRight: 12,
  },
  editButtonText: {
    color: dogThemeColors.primary,
    fontSize: 14,
    fontWeight: "500",
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFE6E6",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: dogThemeColors.warning,
  },
  logoutText: {
    color: dogThemeColors.warning,
    fontSize: 14,
    fontWeight: "500",
  },
  // Enhanced navigation container with dog theme
  enhancedNavigationContainer: {
    backgroundColor: dogThemeColors.cardBg,
    borderRadius: 16,
    padding: 6,
    marginBottom: 20,
    shadowColor: dogThemeColors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 2,
    borderColor: dogThemeColors.lightAccent,
    flexDirection: "row",
  },
  navTab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 2,
    borderRadius: 12,
    marginHorizontal: 1,
  },
  navTabText: {
    fontSize: 9,
    fontWeight: "600",
    marginTop: 2,
    textAlign: "center",
  },
  enhancedNavTabActive: {
    backgroundColor: dogThemeColors.primary,
    shadowColor: dogThemeColors.secondary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 4,
  },
  activeTabIndicator: {
    position: "absolute",
    bottom: 0,
    left: "25%",
    right: "25%",
    height: 3,
    borderRadius: 2,
    backgroundColor: dogThemeColors.accent,
  },
  // Enhanced progress container with dog theme
  enhancedProgressContainer: {
    backgroundColor: dogThemeColors.cardBg,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: dogThemeColors.success,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 2,
    borderColor: dogThemeColors.lightAccent,
  },
  progressHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: dogThemeColors.lightAccent,
  },
  progressTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: dogThemeColors.darkText,
    letterSpacing: 0.5,
  },
  progressStats: {
    alignItems: "center",
  },
  // Enhanced section with dog theme
  enhancedSection: {
    backgroundColor: dogThemeColors.cardBg,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: dogThemeColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 2,
    borderColor: dogThemeColors.lightAccent,
  },
  enhancedSectionTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: dogThemeColors.darkText,
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: dogThemeColors.lightAccent,
  },
  // Enhanced time slot container with dog theme
  enhancedTimeSlotContainer: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderLeftWidth: 6,
    shadowColor: dogThemeColors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: dogThemeColors.lightAccent,
  },
  timeSlotTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  // Enhanced activity row with dog theme
  enhancedActivityRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginVertical: 4,
    borderWidth: 1,
    borderColor: dogThemeColors.lightAccent,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  activityText: {
    fontSize: 16,
    color: dogThemeColors.darkText,
    flex: 1,
    fontWeight: "500",
  },
  activityCompleted: {
    textDecorationLine: "line-through",
    color: dogThemeColors.mediumText,
    opacity: 0.7,
  },
  // Enhanced stage indicator with dog theme
  enhancedStageIndicator: {
    padding: 18,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: dogThemeColors.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 3,
  },
  enhancedStageText: {
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
    letterSpacing: 0.3,
  },
  overviewStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  // Enhanced stat card with dog theme
  enhancedStatCard: {
    flex: 1,
    alignItems: "center",
    backgroundColor: dogThemeColors.lightAccent,
    padding: 20,
    borderRadius: 16,
    marginHorizontal: 6,
    shadowColor: dogThemeColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
  },
  enhancedStatNumber: {
    fontSize: 28,
    fontWeight: "800",
    color: dogThemeColors.primary,
    letterSpacing: 0.5,
  },
  enhancedStatLabel: {
    fontSize: 13,
    color: dogThemeColors.mediumText,
    marginTop: 6,
    textAlign: "center",
    fontWeight: "600",
  },
  enhancedWeekHistoryItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingVertical: 6,
  },
  weekHistoryTitle: {
    fontSize: 14,
    fontWeight: "500",
    color: dogThemeColors.darkText,
    width: 80,
  },
  enhancedProgressBarContainer: {
    flex: 1,
    height: 12,
    backgroundColor: dogThemeColors.lightAccent,
    borderRadius: 6,
    marginHorizontal: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: dogThemeColors.accent,
  },
  enhancedProgressBar: {
    height: "100%",
    backgroundColor: dogThemeColors.success,
    borderRadius: 6,
  },
  weekHistoryPercent: {
    fontSize: 14,
    fontWeight: "500",
    color: dogThemeColors.darkText,
    width: 40,
    textAlign: "right",
  },
  enhancedFamilyMemberRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: dogThemeColors.lightAccent,
    marginBottom: 2,
  },
  familyEditContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  enhancedFamilyEditInput: {
    flex: 1,
    fontSize: 16,
    color: dogThemeColors.darkText,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: dogThemeColors.cardBg,
  },
  enhancedFamilyMemberName: {
    fontSize: 16,
    color: dogThemeColors.darkText,
    flex: 1,
    fontWeight: "500",
  },
  familyActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  familyActionButton: {
    padding: 10,
    marginLeft: 4,
  },
  enhancedAddFamilyContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: dogThemeColors.lightAccent,
  },
  enhancedAddFamilyInput: {
    flex: 1,
    fontSize: 16,
    color: dogThemeColors.darkText,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: dogThemeColors.cardBg,
  },
  enhancedAddFamilyButton: {
    padding: 12,
    marginLeft: 10,
    borderRadius: 8,
    backgroundColor: dogThemeColors.lightAccent,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
  },
  addNoteContainer: {
    flexDirection: "row",
    marginBottom: 16,
  },
  enhancedAddNoteInput: {
    flex: 1,
    fontSize: 16,
    color: dogThemeColors.darkText,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginRight: 10,
    textAlignVertical: "top",
    backgroundColor: dogThemeColors.cardBg,
  },
  enhancedAddNoteButton: {
    backgroundColor: dogThemeColors.primary,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: dogThemeColors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
  },
  notesContainer: {
    marginTop: 8,
  },
  enhancedNoteItem: {
    backgroundColor: dogThemeColors.lightAccent,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
  },
  noteHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  enhancedNoteAuthor: {
    fontSize: 14,
    fontWeight: "600",
    color: dogThemeColors.primary,
  },
  enhancedNoteTimestamp: {
    fontSize: 12,
    color: dogThemeColors.mediumText,
  },
  enhancedNoteText: {
    fontSize: 16,
    color: dogThemeColors.darkText,
    lineHeight: 24,
  },
  enhancedNoteEdited: {
    fontSize: 12,
    color: dogThemeColors.mediumText,
    fontStyle: "italic",
    marginTop: 6,
  },
  noteEditIcon: {
    position: "absolute",
    top: 8,
    right: 8,
    padding: 4,
  },
  noteEditContainer: {
    marginTop: 8,
  },
  enhancedNoteEditInput: {
    fontSize: 16,
    color: dogThemeColors.darkText,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    textAlignVertical: "top",
    backgroundColor: "#fff",
  },
  noteEditActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  noteEditButton: {
    padding: 8,
    marginLeft: 8,
  },
  enhancedNoNotesText: {
    fontSize: 16,
    color: dogThemeColors.mediumText,
    textAlign: "center",
    fontStyle: "italic",
    paddingVertical: 10,
  },
  notesLoader: {
    alignItems: "center",
    marginVertical: 20,
  },
  enhancedNoteInput: {
    fontSize: 16,
    color: dogThemeColors.darkText,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    textAlignVertical: "top",
    backgroundColor: dogThemeColors.cardBg,
    minHeight: 80,
  },
  enhancedAchievementsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  enhancedAchievementStats: {
    marginTop: 20,
    padding: 20,
    backgroundColor: dogThemeColors.lightAccent,
    borderRadius: 16,
    shadowColor: dogThemeColors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 1,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
  },
  enhancedAchievementStatsTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: dogThemeColors.darkText,
    marginBottom: 8,
  },
  enhancedAchievementStatsText: {
    fontSize: 14,
    color: dogThemeColors.mediumText,
    marginBottom: 12,
  },
  weekNavigation: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  weekNavButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: dogThemeColors.lightAccent,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
    minWidth: 80,
    alignItems: "center",
  },
  weekNavDisabled: {
    opacity: 0.5,
  },
  weekNavText: {
    fontSize: 14,
    color: dogThemeColors.primary,
    fontWeight: "600",
    textAlign: "center",
  },
  weekTitleContainer: {
    flex: 1,
    alignItems: "center",
    marginHorizontal: 16,
  },
  weekTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: dogThemeColors.darkText,
    textAlign: "center",
  },
  setupContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
    backgroundColor: dogThemeColors.light,
  },
  welcomeTitle: {
    fontSize: 32,
    fontWeight: "bold",
    color: dogThemeColors.darkText,
    marginBottom: 16,
    textAlign: "center",
  },
  setupText: {
    fontSize: 18,
    color: dogThemeColors.mediumText,
    textAlign: "center",
    marginBottom: 12,
    lineHeight: 26,
  },
  setupSubtext: {
    fontSize: 16,
    color: dogThemeColors.mediumText,
    textAlign: "center",
    marginBottom: 32,
    lineHeight: 22,
    paddingHorizontal: 16,
  },
  setupInput: {
    width: "100%",
    fontSize: 18,
    color: dogThemeColors.darkText,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginBottom: 16,
    backgroundColor: dogThemeColors.cardBg,
  },
  disabledInput: {
    backgroundColor: dogThemeColors.lightAccent,
    color: dogThemeColors.mediumText,
    opacity: 0.7,
  },
  setupButton: {
    width: "100%",
    backgroundColor: dogThemeColors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    shadowColor: dogThemeColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
  },
  setupButtonText: {
    fontSize: 18,
    fontWeight: "700",
    color: dogThemeColors.light,
  },
  pickerInput: {
    fontSize: 18,
    color: dogThemeColors.darkText,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginBottom: 16,
    backgroundColor: dogThemeColors.cardBg,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: dogThemeColors.light,
  },
  loadingText: {
    fontSize: 18,
    color: dogThemeColors.mediumText,
    marginTop: 12,
  },
  syncIndicator: {
    position: "absolute",
    bottom: 100,
    right: 20,
    backgroundColor: dogThemeColors.primary,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 2,
    borderColor: dogThemeColors.accent,
  },
  syncText: {
    color: dogThemeColors.light,
    fontSize: 14,
    fontWeight: "600",
  },
  offlineBanner: {
    backgroundColor: dogThemeColors.warning,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    marginBottom: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#FF4444",
  },
  offlineText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
  },
});